#!/bin/sh
# Minimal reproducible kexec test for Underhill / VTL2 flow.
# Only what is needed to reproduce the original VTL2 protection (AccessDenied)
# issue prior to the init.rs idempotent fix.
set -euo pipefail

echo "[KEXEC] Building minimal initramfs"
INITRD_DIR="/dev/shm/initrd"
rm -rf "$INITRD_DIR"
mkdir -p "$INITRD_DIR" "$INITRD_DIR/bin" "$INITRD_DIR/dev" "$INITRD_DIR/etc" "$INITRD_DIR/run"

# Busybox + init
cp /bin/busybox "$INITRD_DIR/bin/busybox"; chmod 755 "$INITRD_DIR/bin/busybox"
# Add the minimal set of applets we rely on plus extra ones for DTB comparison.
for l in sh mount mkdir echo mknod dd od hexdump printf cmp sha256sum md5sum \
         cat ls stat head wc awk grep dmesg find cut sed tr; do
    ln -sf busybox "$INITRD_DIR/bin/$l" 2>/dev/null || true
done
cp /bin/busybox "$INITRD_DIR/init" && chmod 755 "$INITRD_DIR/init"

# Devices
mknod "$INITRD_DIR/dev/console" c 5 1
mknod "$INITRD_DIR/dev/ttyS2" c 4 66
mknod "$INITRD_DIR/dev/null" c 1 3
mknod "$INITRD_DIR/dev/kmsg" c 1 11
mknod "$INITRD_DIR/dev/mem" c 1 1
mknod "$INITRD_DIR/dev/ttyprintk" c 5 3 || true
chmod 600 "$INITRD_DIR/dev/console" "$INITRD_DIR/dev/ttyS2" "$INITRD_DIR/dev/mem"
chmod 666 "$INITRD_DIR/dev/null" "$INITRD_DIR/dev/kmsg"
[ -e "$INITRD_DIR/dev/ttyprintk" ] || ln -sf kmsg "$INITRD_DIR/dev/ttyprintk"

# Underhill binary
TARGET=$(readlink -f /underhill-init 2>/dev/null || echo /usr/bin/openvmm_hcl)
[ -f "$TARGET" ] || { echo "[KEXEC] ERROR: underhill binary not found at $TARGET" >&2; exit 1; }
cp "$TARGET" "$INITRD_DIR/underhill-init"
cp "$TARGET" "$INITRD_DIR/bin/openvmm_hcl"
chmod 755 "$INITRD_DIR/underhill-init" "$INITRD_DIR/bin/openvmm_hcl"

# Module staging (updated layout: modules are flat under /boot/modules)
echo "[KEXEC] Staging required kernel modules"
mkdir -p "$INITRD_DIR/lib/modules"
stage_mod() {
    m=$1; src="/boot/modules/$m"; dst="$INITRD_DIR/lib/modules/$m";
    if [ -f "$src" ]; then
        cp "$src" "$dst"
    else
        echo "[KEXEC] WARN missing $src" >&2
    fi
}
stage_mod pci-hyperv-intf.ko
stage_mod pci-hyperv.ko
stage_mod hv_storvsc.ko

# Helper to (re)build initramfs archive from INITRD_DIR into target path.
build_initrd() {
    target=$1
    ( cd "$INITRD_DIR" && find . -print0 | cpio --null -o -H newc | gzip -1 > "$target.tmp" )
    mv -f "$target.tmp" "$target"
}

# ---------------------------------------------------------------------------
# Capture measured VTL0 config + VP context (for rehydration after kexec)
# ---------------------------------------------------------------------------
# This captures:
#   * Raw page 0 (ParavisorMeasuredVtl0Config)
#   * Optional VP context page (if descriptor points to one)
#   * Metadata (hashes, descriptor values, register_count)
# Files are deposited inside the initramfs at /vtl0_capture/ so the next
# kernel/init path can rehydrate the measured config rather than relying on
# synthetic environment overrides.
#
# Control with CAPTURE_VTL0 (default=1). Set CAPTURE_VTL0=0 to skip.
# ---------------------------------------------------------------------------

if [ "${CAPTURE_VTL0:-1}" = "1" ]; then
    echo "[KEXEC] Capturing VTL0 measured config (page 0)"
    CAP_DIR="$INITRD_DIR/vtl0_capture"
    mkdir -p "$CAP_DIR"
    PAGE0_FILE="$CAP_DIR/page0.bin"
    VP_FILE="$CAP_DIR/vp_context.bin"
    META_FILE="$CAP_DIR/meta.txt"

    # Read raw page 0 (4 KiB)
    if dd if=/dev/mem of="$PAGE0_FILE" bs=4096 count=1 skip=0 2>/dev/null; then
        :
    else
        echo "[KEXEC] WARN: failed to read page 0 from /dev/mem; skipping capture" >&2
    fi

    if [ -s "$PAGE0_FILE" ]; then
        # Helper: read little-endian 64-bit at offset (bytes)
        read_u64_dec() { off=$1; dd if="$PAGE0_FILE" bs=1 skip=$off count=8 2>/dev/null | od -An -tu8 | tr -d ' \n'; }
        read_u64_hex() { off=$1; dd if="$PAGE0_FILE" bs=1 skip=$off count=8 2>/dev/null | od -An -tx8 | tr -d ' \n'; }

        MAGIC_HEX=$(read_u64_hex 0 || echo "")
        SUPPORTED_HEX=$(read_u64_hex 8 || echo "")

        # PageRegionDescriptor firmware at offset 16
        FIRMWARE_BASE_PAGE=$(read_u64_dec 16 || echo 0)
        FIRMWARE_PAGE_COUNT=$(read_u64_dec 24 || echo 0)
        # vtl0_vp_context descriptor at offset 40
        VP_BASE_PAGE=$(read_u64_dec 40 || echo 0)
        VP_PAGE_COUNT=$(read_u64_dec 48 || echo 0)

        # Derive flags
        # Bit 0 of supported_vtl0 => UEFI supported
        UEFI_SUPPORTED=0
        if [ -n "$SUPPORTED_HEX" ]; then
            # Convert hex (little-endian machine order shown by od) to decimal using printf
            # shellcheck disable=SC2059
            SUP_DEC=$(( 0x${SUPPORTED_HEX} ))
            if [ $(( SUP_DEC & 0x1 )) -ne 0 ]; then UEFI_SUPPORTED=1; fi
        fi

        # Try to capture VP context page if descriptor valid
        REGISTER_COUNT=""
        if [ "$VP_BASE_PAGE" -gt 0 ] && [ "$VP_PAGE_COUNT" -eq 1 ]; then
            echo "[KEXEC] Capturing VP context page (base page=$VP_BASE_PAGE)"
            if dd if=/dev/mem of="$VP_FILE" bs=4096 count=1 skip="$VP_BASE_PAGE" 2>/dev/null; then
                # First 4 bytes = register_count (u32 little-endian)
                REGISTER_COUNT=$(dd if="$VP_FILE" bs=4 count=1 2>/dev/null | od -An -tu4 | tr -d ' \n')
            else
                echo "[KEXEC] WARN: failed to read VP context page" >&2
                rm -f "$VP_FILE"
            fi
        fi

        PAGE0_HASH=$(sha256sum "$PAGE0_FILE" 2>/dev/null | awk '{print $1}')
        if [ -f "$VP_FILE" ]; then
            VP_HASH=$(sha256sum "$VP_FILE" 2>/dev/null | awk '{print $1}')
        else
            VP_HASH=""
        fi

        {
            echo "magic=0x$MAGIC_HEX"
            echo "supported_vtl0=0x$SUPPORTED_HEX"
            echo "uefi_supported=$UEFI_SUPPORTED"
            echo "firmware_base_page=$FIRMWARE_BASE_PAGE"
            echo "firmware_page_count=$FIRMWARE_PAGE_COUNT"
            echo "vp_page_base=$VP_BASE_PAGE"
            echo "vp_page_count=$VP_PAGE_COUNT"
            echo "register_count=$REGISTER_COUNT"
            echo "page0_sha256=$PAGE0_HASH"
            echo "vp_context_sha256=$VP_HASH"
            # Convenience: also dump first 64 bytes of page0 as hex for quick visual diff
            echo -n "page0_first64="
            head -c 64 "$PAGE0_FILE" 2>/dev/null | od -An -tx1 | tr -d ' \n'
            echo
        } > "$META_FILE"
        chmod 600 "$PAGE0_FILE" "$META_FILE" 2>/dev/null || true
        [ -f "$VP_FILE" ] && chmod 600 "$VP_FILE" 2>/dev/null || true
        echo "[KEXEC] Capture complete: $(wc -c < "$PAGE0_FILE") bytes page0; VP page present: $( [ -f "$VP_FILE" ] && echo yes || echo no )"
    fi
else
    echo "[KEXEC] Skipping VTL0 capture (CAPTURE_VTL0=0)"
fi

# (DTB comparison & EFI forcing logic removed to keep script minimal.)

# Initramfs
IMG_PATH="/tmp/initramfs.gz"
build_initrd "$IMG_PATH"

# Verify that vtl0_capture made it into the archive; if not, warn early.
echo "[KEXEC] Verifying presence of vtl0_capture in initramfs"
if gzip -dc "$IMG_PATH" | cpio -t 2>/dev/null | grep -q "^vtl0_capture/"; then
    echo "[KEXEC] vtl0_capture directory present in initramfs"
else
    echo "[KEXEC] WARN: vtl0_capture directory NOT found in initramfs list" >&2
fi

# Extra resilience: pack capture into a single tarball as fallback if directory lost due to pivot.
if [ -d "$INITRD_DIR/vtl0_capture" ]; then
    ( cd "$INITRD_DIR" && tar -cf vtl0_capture.tar vtl0_capture 2>/dev/null || true )
    if [ -f "$INITRD_DIR/vtl0_capture.tar" ]; then
        # Rebuild archive to include the tarball if newly created after first pass.
        build_initrd "$IMG_PATH"
        echo "[KEXEC] Added vtl0_capture.tar to initramfs"
    fi
fi

# ---------------------------------------------------------------------------
# Optional in-place rehydration of synthetic VTL0 measured config (page 0)
# ---------------------------------------------------------------------------
# Goal: populate ParavisorMeasuredVtl0Config so the next kernel's loader
# sees UEFI support without needing binary rebuild or env override.
#
# Controlled by REHYDRATE_VTL0=1 (default 0). This writes page 0 fields:
#   magic = "OHCLVTL0"
#   supported_vtl0: uefi_supported bit set (others clear)
#   uefi_info.firmware: base_page = FIRMWARE_BASE/4096, page_count = FIRMWARE_SIZE/4096
#   vtl0_vp_context descriptor optionally points at a synthetic VP context page
# LinuxInfo left zeroed.
#
# Override defaults via env:
#   FIRMWARE_BASE          (hex or decimal, default 0x100000)
#   FIRMWARE_SIZE          (hex or decimal, default 0x600000)
#   SYNTH_VTL0_VP_CONTEXT  (1 to synthesize VP context page, default 0 for now)
#   VP_CONTEXT_BASE_PAGE   (decimal page number, default firmware_end_page)
#   VP_CONTEXT_PAGE_COUNT  (default 1)
#
# NOTE: PageRegionDescriptor is only two u64 values (base_page_number, page_count).
# Previous version of this script incorrectly inserted an "accepted" byte and
# padding (like ImportedRegionDescriptor), corrupting offsets so the loader
# observed vtl0_vp_context.base_page_number == 0 and panicked. That extra field
# is now removed.
#
# Safety: only proceed if /dev/mem writable and page 0 readable. Always backs
# up original page0 to /tmp/page0.pre_rehydrate.bin for inspection.
# ---------------------------------------------------------------------------
if [ "${REHYDRATE_VTL0:-0}" = "1" ]; then
    echo "[KEXEC] Rehydrating synthetic VTL0 measured config (page 0)"
    : "${FIRMWARE_BASE:=0x100000}" "${FIRMWARE_SIZE:=0x600000}"
    # Normalize to decimal using shell arithmetic (supports 0x prefix)
    FW_BASE_DEC=$((FIRMWARE_BASE))
    FW_SIZE_DEC=$((FIRMWARE_SIZE))
    if [ $(( FW_BASE_DEC % 4096 )) -ne 0 ]; then
        echo "[KEXEC] ERROR: FIRMWARE_BASE must be 4K aligned" >&2; exit 1;
    fi
    if [ $(( FW_SIZE_DEC % 4096 )) -ne 0 ]; then
        echo "[KEXEC] ERROR: FIRMWARE_SIZE must be multiple of 4K" >&2; exit 1;
    fi
    FW_BASE_PAGE=$(( FW_BASE_DEC / 4096 ))
    FW_PAGE_COUNT=$(( FW_SIZE_DEC / 4096 ))

    # Temporarily default off until VP context register format mismatch resolved.
    : "${SYNTH_VTL0_VP_CONTEXT:=0}"
    : "${VP_CONTEXT_PAGE_COUNT:=1}"
    if [ "$SYNTH_VTL0_VP_CONTEXT" = "1" ]; then
        if [ -z "${VP_CONTEXT_BASE_PAGE:-}" ]; then
            VP_CONTEXT_BASE_PAGE=$(( FW_BASE_PAGE + FW_PAGE_COUNT ))
        fi
        if [ "$VP_CONTEXT_PAGE_COUNT" -lt 1 ]; then
            echo "[KEXEC] ERROR: VP_CONTEXT_PAGE_COUNT must be >= 1" >&2; exit 1;
        fi
    else
        VP_CONTEXT_BASE_PAGE=0
        VP_CONTEXT_PAGE_COUNT=0
    fi

    # Back up existing page 0
    dd if=/dev/mem of=/tmp/page0.pre_rehydrate.bin bs=4096 count=1 skip=0 2>/dev/null || true

    TMP_PAGE=/tmp/page0.rehydrate.bin
    # Create zero page
    dd if=/dev/zero of="$TMP_PAGE" bs=4096 count=1 2>/dev/null

    # Helper to append 64-bit LE value
    append_u64_le() {
        v=$1
        bytes=""
        for shift in 0 8 16 24 32 40 48 56; do
            byte=$(((v >> shift) & 0xFF ))
            bytes="${bytes}\\x$(printf '%02x' "$byte")"
        done
        printf '%b' "$bytes"
    }

    # Build the first 0x40 bytes in a single temp header file
    HDR=/tmp/page0.header.bin
    {
        # magic "OHCLVTL0" (0x4F48434C56544C30 little-endian)
        printf '\x30\x4c\x54\x56\x4c\x43\x48\x4f'
        # supported_vtl0 (bit0=UEFI) => 1
        append_u64_le 1
        # firmware base_page_number
        append_u64_le $FW_BASE_PAGE
        # firmware page_count
        append_u64_le $FW_PAGE_COUNT
        # (No accepted flag for PageRegionDescriptor; next comes vp_context descriptor)
        if [ "$SYNTH_VTL0_VP_CONTEXT" = "1" ]; then
            # vtl0_vp_context descriptor populated
            append_u64_le "$VP_CONTEXT_BASE_PAGE"
            append_u64_le "$VP_CONTEXT_PAGE_COUNT"
        else
            append_u64_le 0
            append_u64_le 0
        fi
    } > "$HDR"

    # Write header into zero page
    dd if="$HDR" of="$TMP_PAGE" bs=1 conv=notrunc 2>/dev/null

    # Sanity dump (hex of first 64 bytes)
    HEX_PREFIX=$(hexdump -v -n64 -e '64/1 "%02x"' "$TMP_PAGE" 2>/dev/null || echo "")
    echo "[KEXEC] Synthetic page0 header hex64=$HEX_PREFIX"
    echo "[KEXEC]  magic=OHCLVTL0 firmware_base=0x$(printf %x $FW_BASE_DEC) firmware_size=0x$(printf %x $FW_SIZE_DEC) pages=$FW_PAGE_COUNT"
    # Quick decode of descriptor values from the temp page for verification
    fw_base_verify=$(dd if="$TMP_PAGE" bs=1 skip=16 count=8 2>/dev/null | od -An -tu8 | tr -d ' \n') || fw_base_verify=0
    fw_cnt_verify=$(dd if="$TMP_PAGE" bs=1 skip=24 count=8 2>/dev/null | od -An -tu8 | tr -d ' \n') || fw_cnt_verify=0
    vp_base_verify=$(dd if="$TMP_PAGE" bs=1 skip=32 count=8 2>/dev/null | od -An -tu8 | tr -d ' \n') || vp_base_verify=0
    vp_cnt_verify=$(dd if="$TMP_PAGE" bs=1 skip=40 count=8 2>/dev/null | od -An -tu8 | tr -d ' \n') || vp_cnt_verify=0
    echo "[KEXEC]  verify firmware(base=$fw_base_verify count=$fw_cnt_verify) vp_context(base=$vp_base_verify count=$vp_cnt_verify)"
    if [ "$SYNTH_VTL0_VP_CONTEXT" = "1" ] && { [ "$vp_base_verify" -eq 0 ] || [ "$vp_cnt_verify" -ne 1 ]; }; then
        echo "[KEXEC] ERROR: VP context descriptor malformed (expected base>0,count=1)" >&2
        exit 1
    fi

    # Write to physical page 0
    if dd if="$TMP_PAGE" of=/dev/mem bs=4096 count=1 seek=0 conv=notrunc 2>/dev/null; then
        echo "[KEXEC] Wrote synthetic measured config to page 0"
    else
        echo "[KEXEC] ERROR: failed writing synthetic measured config to /dev/mem" >&2
    fi

    if [ "$SYNTH_VTL0_VP_CONTEXT" = "1" ]; then
        if ! command -v base64 >/dev/null 2>&1; then
            echo "[KEXEC] ERROR: base64 utility required to synthesize VP context" >&2; exit 1;
        fi
        VP_CONTEXT_TMP=/tmp/vtl0_vp_context.rehydrate.bin
        cat <<'EOF' | base64 -d > "$VP_CONTEXT_TMP"
FQAAAAABAAcAAAAAAAAAAAAAAAAAAAAAAAAfAABgcAAAAAAAAAMABgAAAAAAAAAAAAAAAAAAAAAAAAAA/////xAAk8AAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8QAJPAAAYABgAAAAAAAAAAAAAAAAAAAAAAAAAA/////xAAk8AAAgAGAAAAAAAAAAAAAAAAAAAAAAAAAAD/////EACTwAABAAYAAAAAAAAAAAAAAAAAAAAAAAAAAP////8IAJugAAAABAAAAAAAAAAAAAAAACMAAIAAAAAAAAAAAAAAAAAAAgAEAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAADAAQAAAAAAAAAAAAAAABgBgAAAAAAAAAAAAAAAAAAAAEACAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAABAAIAAAAAAAAAAAAAAAABgQHAAYEBwAAAAAAAAAAAAAFAAIAAAAAAAAAAAAAAAAAAG4AAAAAAAAAAAAAAAAAABAAAgAAAAAAAAAAAAAAAEQqbgAAAAAAAAAAAAAAAAAACAACAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAJAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAgAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAHAACAAAAAAAAAAAAAAAAAYGBgYGBgYGAAAAAAAAAAAAcQAIAAAAAAAAAAAAAAAABgYGBgYGBgYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
EOF
        if dd if="$VP_CONTEXT_TMP" of=/dev/mem bs=4096 count="$VP_CONTEXT_PAGE_COUNT" seek="$VP_CONTEXT_BASE_PAGE" conv=notrunc 2>/dev/null; then
            echo "[KEXEC] Wrote synthetic VP context to page(s) starting at $VP_CONTEXT_BASE_PAGE"
            # Inspect header register_count (first 4 bytes little-endian u32)
            REG_COUNT_SYNTH=$(dd if="$VP_CONTEXT_TMP" bs=4 count=1 2>/dev/null | od -An -tu4 | tr -d ' \n') || REG_COUNT_SYNTH="?"
            echo "[KEXEC] VP context synth header register_count=$REG_COUNT_SYNTH"
        else
            echo "[KEXEC] ERROR: failed writing VP context to /dev/mem" >&2
        fi
    fi

    if [ "${CAPTURE_VTL0_POST:-1}" = "1" ]; then
        echo "[KEXEC] Capturing rehydrated VTL0 measured config"
        POST_DIR="$INITRD_DIR/vtl0_capture_post"
        mkdir -p "$POST_DIR"
        POST_PAGE="$POST_DIR/page0.bin"
        if dd if=/dev/mem of="$POST_PAGE" bs=4096 count=1 skip=0 2>/dev/null; then
            cp "$POST_PAGE" /tmp/page0.post_rehydrate.bin 2>/dev/null || true

            read_u64_dec_post() {
                dd if="$POST_PAGE" bs=1 skip=$1 count=8 2>/dev/null | od -An -tu8 | tr -d ' \n'
            }
            read_u64_hex_post() {
                dd if="$POST_PAGE" bs=1 skip=$1 count=8 2>/dev/null | od -An -tx8 | tr -d ' \n'
            }

            MAGIC_HEX_POST=$(read_u64_hex_post 0 || echo "")
            SUPPORTED_HEX_POST=$(read_u64_hex_post 8 || echo "")
            FW_BASE_PAGE_POST=$(read_u64_dec_post 16 || echo 0)
            FW_PAGE_COUNT_POST=$(read_u64_dec_post 24 || echo 0)
            VP_BASE_PAGE_POST=$(read_u64_dec_post 40 || echo 0)
            VP_PAGE_COUNT_POST=$(read_u64_dec_post 48 || echo 0)

            UEFI_SUPPORTED_POST=0
            if [ -n "$SUPPORTED_HEX_POST" ]; then
                SUP_DEC_POST=$(( 0x${SUPPORTED_HEX_POST} ))
                if [ $(( SUP_DEC_POST & 0x1 )) -ne 0 ]; then UEFI_SUPPORTED_POST=1; fi
            fi

            VP_POST_FILE=""
            VP_POST_SHA=""
            if [ "$SYNTH_VTL0_VP_CONTEXT" = "1" ] && [ "$VP_CONTEXT_BASE_PAGE" -gt 0 ]; then
                VP_POST_FILE="$POST_DIR/vp_context.bin"
                if dd if=/dev/mem of="$VP_POST_FILE" bs=4096 count="$VP_CONTEXT_PAGE_COUNT" skip="$VP_CONTEXT_BASE_PAGE" 2>/dev/null; then
                    VP_POST_SHA=$(sha256sum "$VP_POST_FILE" 2>/dev/null | awk '{print $1}')
                    cp "$VP_POST_FILE" /tmp/vp_context.post_rehydrate.bin 2>/dev/null || true
                    REG_COUNT_POST=$(dd if="$VP_POST_FILE" bs=4 count=1 2>/dev/null | od -An -tu4 | tr -d ' \n') || REG_COUNT_POST="?"
                    echo "[KEXEC] VP context post header register_count=$REG_COUNT_POST"
                else
                    echo "[KEXEC] WARN: failed to capture VP context page" >&2
                    rm -f "$VP_POST_FILE"
                    VP_POST_FILE=""
                fi
            fi

            POST_META="$POST_DIR/meta.txt"
            {
                echo "magic=0x$MAGIC_HEX_POST"
                echo "supported_vtl0=0x$SUPPORTED_HEX_POST"
                echo "uefi_supported=$UEFI_SUPPORTED_POST"
                echo "firmware_base_page=$FW_BASE_PAGE_POST"
                echo "firmware_page_count=$FW_PAGE_COUNT_POST"
                echo "vp_page_base=$VP_BASE_PAGE_POST"
                echo "vp_page_count=$VP_PAGE_COUNT_POST"
                echo -n "page0_first64="
                head -c 64 "$POST_PAGE" 2>/dev/null | od -An -tx1 | tr -d ' \n'
                echo
                echo "page0_sha256=$(sha256sum "$POST_PAGE" 2>/dev/null | awk '{print $1}')"
                if [ -n "$VP_POST_SHA" ]; then
                    echo "vp_context_sha256=$VP_POST_SHA"
                fi
            } > "$POST_META"
            chmod 600 "$POST_PAGE" "$POST_META" 2>/dev/null || true
            [ -n "$VP_POST_FILE" ] && chmod 600 "$VP_POST_FILE" 2>/dev/null || true
            echo "[KEXEC] Stored rehydrated page0 + metadata under vtl0_capture_post/"
            build_initrd "$IMG_PATH"
        else
            echo "[KEXEC] WARN: could not read rehydrated page0 for capture" >&2
        fi
    fi
fi

# Kernel cmdline (original reproduction set)
RDINIT_TARGET="/underhill-init"
if [ "${USE_UNDERHILL_WRAPPER:-1}" = "1" ]; then
    WRAPPER_PATH="$INITRD_DIR/underhill-wrapper.sh"
    cat > "$WRAPPER_PATH" <<'EOF'
#!/bin/sh
set -eu
log() { echo "[WRAPPER] $*" >&2; }
copy_capture_dir() {
    src="$1"
    dst="/run/$1"
    if [ -d "$src" ]; then
        mkdir -p "$dst"
        cp -a "$src/." "$dst/" 2>/dev/null || true
        log "copied $src to $dst"
    fi
}
copy_capture_dir vtl0_capture
copy_capture_dir vtl0_capture_post
exec /underhill-init "$@"
EOF
    chmod 755 "$WRAPPER_PATH"
    RDINIT_TARGET="/underhill-wrapper.sh"
fi

CMDLINE="loglevel=8 log_buf_len=128K printk.time=1 console_msg_format=syslog"
CMDLINE="$CMDLINE uio_hv_generic.no_mask=1 coredump_filter=0x33"
CMDLINE="$CMDLINE cpufreq.off=1 cpuidle.off=1 cryptomgr.notests idle=halt"
CMDLINE="$CMDLINE initcall_blacklist=init_real_mode,sbf_init lpj=3000000"
CMDLINE="$CMDLINE no_timer_check noxsave oops=panic panic_on_warn=0 panic_print=0 panic=-1"
CMDLINE="$CMDLINE printk.devkmsg=on reboot=t rootfstype=tmpfs tsc=reliable unknown_nmi_panic=1"
CMDLINE="$CMDLINE vfio_pci.ids=1414:00ba vfio.enable_unsafe_noiommu_mode=1"
CMDLINE="$CMDLINE hv_storvsc.storvsc_vcpus_per_sub_channel=2048 hv_storvsc.storvsc_max_hw_queues=2 hv_storvsc.storvsc_ringbuffer_size=0x8000"
CMDLINE="$CMDLINE MIMALLOC_ARENA_EAGER_COMMIT=0"
CMDLINE="$CMDLINE clearcpuid=pcid iommu=off pci=off swiotlb=1,1"
CMDLINE="$CMDLINE console=ttyS2,115200 boot_cpus=0 hv_vmbus.message_connection_id=0x800074"
CMDLINE="$CMDLINE rdinit=$RDINIT_TARGET UNDERHILL_DIAG=1 HVLITE_LOG=debug RUST_BACKTRACE=full OPENHCL_NVME_VFIO=1"
CMDLINE="$CMDLINE OPENHCL_SIDECAR=log"
[ -n "${EXTRA_CMDLINE:-}" ] && CMDLINE="$CMDLINE $EXTRA_CMDLINE"

if [ "${PRINT_VTL0_POST:-0}" = "1" ]; then
    if [ -f /tmp/page0.post_rehydrate.bin ]; then
        echo "[KEXEC] --- BEGIN page0.post_rehydrate.bin (hex) ---"
        hexdump -C /tmp/page0.post_rehydrate.bin | sed 's/^/[KEXEC] /'
        echo "[KEXEC] --- END page0.post_rehydrate.bin ---"
        echo "[KEXEC] page0.post_rehydrate.sha256=$(sha256sum /tmp/page0.post_rehydrate.bin | awk '{print $1}')"
    else
        echo "[KEXEC] WARN: /tmp/page0.post_rehydrate.bin not found for printing" >&2
    fi
fi

if [ "${PAUSE_BEFORE_KEXEC:-0}" = "1" ]; then
    echo "[KEXEC] PAUSE_BEFORE_KEXEC set; press Enter to continue with kexec..."
    # shellcheck disable=SC2034
    read _ || true
fi

# Locate measured VTL2 config page
echo "[KEXEC] Locating measured VTL2 config page"
parse_reg() { b=$(hexdump -v -n16 -e '16/1 "%02x"' "$1" 2>/dev/null || true); [ -z "$b" ] && return 1; a_hi=${b:0:8}; a_lo=${b:8:8}; s_hi=${b:16:8}; s_lo=${b:24:8}; REG_ADDR=$(( (0x$a_hi << 32) | 0x$a_lo )); REG_SIZE=$(( (0x$s_hi << 32) | 0x$s_lo )); }
ACCEPTED_BASE=
for f in /proc/device-tree/openhcl/memory@*/reg; do [ -f "$f" ] || continue; parse_reg "$f" || continue; if [ "$REG_SIZE" -eq 8192 ]; then ACCEPTED_BASE=$REG_ADDR; break; fi; done
[ -n "$ACCEPTED_BASE" ] || { echo "[KEXEC] ERROR: 8K accepted+measured region not found" >&2; exit 1; }
MEASURED_ADDR=$((ACCEPTED_BASE + 0x1000))
printf '[KEXEC] accepted_base=0x%016x measured_page=0x%016x\n' "$ACCEPTED_BASE" "$MEASURED_ADDR"

EXPECT=324c54564c43484f
CUR=$(dd if=/dev/mem bs=8 count=1 skip=$((MEASURED_ADDR/8)) 2>/dev/null | od -An -tx1 | tr -d ' \n')
echo "[KEXEC] current_magic=$CUR expect=$EXPECT"
if [ "$CUR" != "$EXPECT" ]; then
    printf '\x32\x4c\x54\x56\x4c\x43\x48\x4f' | dd of=/dev/mem bs=8 count=1 seek=$((MEASURED_ADDR/8)) conv=notrunc 2>/dev/null
    CUR=$(dd if=/dev/mem bs=8 count=1 skip=$((MEASURED_ADDR/8)) 2>/dev/null | od -An -tx1 | tr -d ' \n')
    echo "[KEXEC] magic_after=$CUR"
fi
[ "$CUR" = "$EXPECT" ] || { echo "[KEXEC] ERROR: failed to set magic" >&2; exit 1; }

# Patch VTL0 config magic at physical page 0 (needed to avoid second assert in vtl0_config.rs)
VTL0_EXPECT=304c54564c43484f
VTL0_CUR=$(dd if=/dev/mem bs=8 count=1 skip=0 2>/dev/null | od -An -tx1 | tr -d ' \n')
echo "[KEXEC] vtl0_current_magic=$VTL0_CUR expect=$VTL0_EXPECT"
if [ "$VTL0_CUR" != "$VTL0_EXPECT" ]; then
    printf '\x30\x4c\x54\x56\x4c\x43\x48\x4f' | dd of=/dev/mem bs=8 count=1 seek=0 conv=notrunc 2>/dev/null
    VTL0_CUR=$(dd if=/dev/mem bs=8 count=1 skip=0 2>/dev/null | od -An -tx1 | tr -d ' \n')
    echo "[KEXEC] vtl0_magic_after=$VTL0_CUR"
fi
[ "$VTL0_CUR" = "$VTL0_EXPECT" ] || { echo "[KEXEC] ERROR: failed to set VTL0 magic" >&2; exit 1; }

echo "[KEXEC] Loading kernel with cmdline: $CMDLINE"
/bin/echo "[KEXEC] Final kernel cmdline length: ${#CMDLINE} chars"
/sbin/kexec -l /boot/bzImage --initrd="$IMG_PATH" --command-line="$CMDLINE" --reset-vga
echo "[KEXEC] Executing kexec"
exec /sbin/kexec -e
