#!/bin/bash
set -e

echo "============================================================================"
echo "  OHCL Linux Kernel - Reproducible Build Dependency Installer"
echo "============================================================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "ERROR: This script must be run as root"
    echo "Usage: sudo $0"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    DETECTED_OS=$ID
    DETECTED_VERSION=$VERSION_ID
    DETECTED_OS_NAME=$PRETTY_NAME
else
    echo "ERROR: Cannot detect OS. /etc/os-release not found."
    exit 1
fi

echo "Detected OS: $DETECTED_OS_NAME"
echo ""

# Verify Ubuntu (recommended for reproducibility)
if [ "$DETECTED_OS" != "ubuntu" ]; then
    echo "WARNING: This script is designed and tested for Ubuntu."
    echo "Your OS: $DETECTED_OS_NAME"
    echo ""
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 1
    fi
fi

if [ "$DETECTED_OS" = "ubuntu" ] && [ "$DETECTED_VERSION" != "22.04" ]; then
    echo "NOTE: This script targets Ubuntu 22.04 LTS for reproducibility."
    echo "Your version: $DETECTED_VERSION"
    echo "Installation will proceed, but toolchain versions may differ."
    echo ""
fi

# Update package database
echo "Updating package database..."
apt-get update

echo ""
echo "=== Installing Core Toolchain ==="

# Install gcc-11 specifically (for reproducibility)
echo "Installing GCC 11..."
apt-get install -y \
    gcc-11 \
    g++-11 \
    build-essential

# Set gcc-11 as default
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 || true
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100 || true

# Install binutils and make
apt-get install -y \
    binutils \
    make

echo ""
echo "=== Installing Build Utilities ==="

apt-get install -y \
    flex \
    bison \
    bc \
    rsync \
    cpio \
    kmod \
    wget \
    git

echo ""
echo "=== Installing Development Libraries ==="

apt-get install -y \
    libelf-dev \
    libssl-dev \
    libncurses-dev \
    libklibc-dev \
    musl-tools

echo ""
echo "=== Installing Kernel-Specific Dependencies ==="

apt-get install -y \
    execstack \
    xmlstarlet

echo ""
echo "=== Installing Cross-Compilation Support ==="

apt-get install -y \
    gcc-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu

echo ""
echo "=== Installing Perf Build Dependencies ==="

apt-get install -y \
    libdw-dev \
    libbz2-dev \
    libunwind-dev \
    libbfd-dev \
    libiberty-dev \
    libzstd-dev \
    python3 \
    python3-dev

echo ""
echo "=== Installing Mono (for build pipeline) ==="

apt-get install -y --no-install-recommends gnupg ca-certificates

# Add Mono repository
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF 2>/dev/null || \
    echo "Note: Could not add Mono GPG key, repository may already be configured"

if [ ! -f /etc/apt/sources.list.d/mono-official-stable.list ]; then
    echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    apt-get update
fi

apt-get install -y mono-devel

echo ""
echo "=== Installing Optional Reproducibility Tools ==="

# Install diffoscope for reproducibility verification (optional)
apt-get install -y diffoscope 2>/dev/null || \
    echo "Note: diffoscope not available (optional tool for build comparison)"

echo ""
echo "=== Recording Installed Versions ==="

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Helper functions to extract versions
get_version_number() {
    echo "$1" | grep -oP '\d+\.\d+(\.\d+)?' | head -1
}

# Record all versions
cat > "${SCRIPT_DIR}/TOOLCHAIN_VERSIONS" << EOF
# Reproducible Build Environment Record
# Auto-generated by install-deps.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# This file records the exact versions of all build dependencies.
# Subsequent builds will verify against these versions to ensure reproducibility.

[CRITICAL - Toolchain]
# These directly affect binary output - must match for reproducibility
GCC_VERSION=$(gcc --version | head -n1 | grep -oP '\d+\.\d+\.\d+')
GCC_FULL=$(gcc --version | head -n1)
BINUTILS_VERSION=$(ld --version | head -n1 | grep -oP '\d+\.\d+')
LD_VERSION=$(ld --version | head -n1 | grep -oP '\d+\.\d+')
LD_FULL=$(ld --version | head -n1)
MAKE_VERSION=$(make --version | head -n1 | grep -oP '\d+\.\d+')
MAKE_FULL=$(make --version | head -n1)

[IMPORTANT - Build Tools]
# These can affect generated code - version differences cause warnings
FLEX_VERSION=$(flex --version 2>&1 | head -n1 | grep -oP '\d+\.\d+\.\d+' || echo "unknown")
BISON_VERSION=$(bison --version | head -n1 | grep -oP '\d+\.\d+(\.\d+)?' || echo "unknown")
BC_VERSION=$(bc --version 2>&1 | head -n1 | grep -oP '\d+\.\d+\.\d+' || echo "unknown")
PYTHON_VERSION=$(python3 --version | grep -oP '\d+\.\d+')
RSYNC_VERSION=$(rsync --version | head -n1 | grep -oP '\d+\.\d+\.\d+' || echo "unknown")

[TRACKED - Libraries]
# These are documented but don't usually affect kernel binary
LIBELF_VERSION=$(dpkg -s libelf-dev 2>/dev/null | grep '^Version:' | awk '{print $2}' | cut -d'-' -f1 || echo "unknown")
LIBSSL_VERSION=$(dpkg -s libssl-dev 2>/dev/null | grep '^Version:' | awk '{print $2}' | cut -d'-' -f1 || echo "unknown")

[OPTIONAL - Cross Compilation]
# Only needed for ARM64 builds
ARM64_GCC_VERSION=$(aarch64-linux-gnu-gcc --version 2>/dev/null | head -n1 | grep -oP '\d+\.\d+\.\d+' || echo "not_installed")

[ENVIRONMENT]
# System information for complete reproducibility record
OS_RELEASE=$DETECTED_OS_NAME
BUILD_KERNEL=$(uname -r)
ARCH=$(uname -m)
INSTALL_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
INSTALLER_USER=$SUDO_USER
EOF

echo ""
echo "============================================================================"
echo "  Installation Complete!"
echo "============================================================================"
echo ""
echo "Toolchain versions recorded in: ${SCRIPT_DIR}/TOOLCHAIN_VERSIONS"
echo ""
echo "Installed versions:"
echo "  GCC:      $(gcc --version | head -n1 | grep -oP '\d+\.\d+\.\d+')"
echo "  Make:     $(make --version | head -n1 | grep -oP '\d+\.\d+')"
echo "  Binutils: $(ld --version | head -n1 | grep -oP '\d+\.\d+')"
echo "  Flex:     $(flex --version 2>&1 | head -n1 | grep -oP '\d+\.\d+\.\d+' || echo 'installed')"
echo "  Bison:    $(bison --version | head -n1 | grep -oP '\d+\.\d+(\.\d+)?' || echo 'installed')"
echo "  Python:   $(python3 --version | grep -oP '\d+\.\d+')"
echo ""
echo "Next steps:"
echo "  1. cd $(dirname "$SCRIPT_DIR")"
echo "  2. ./Microsoft/build-hcl-kernel.sh x64"
echo ""
echo "For reproducible builds, all future builds should use these exact versions."
echo "============================================================================"
