#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Reproducible kernel build script for NixOS
# This script ensures consistent build environment for reproducible builds

set -euo pipefail

# Auto-detect and enter Nix environment if not already in one
if [ -z "${IN_NIX_SHELL:-}" ]; then
    # Check if nix is available
    if ! command -v nix &> /dev/null; then
        # Try to source nix profile
        if [ -f ~/.nix-profile/etc/profile.d/nix.sh ]; then
            . ~/.nix-profile/etc/profile.d/nix.sh
        else
            echo "Error: Nix is not installed or not in PATH"
            echo "Please run: ./Microsoft/nix-setup.sh"
            exit 1
        fi
    fi

    # Re-execute this script inside nix develop with experimental features enabled
    exec nix --extra-experimental-features "nix-command flakes" develop --command "$0" "$@"
fi

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KERNEL_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Parse architecture and build type from command line
ARCH_TYPE="${1:-x64}"  # Default to x64
BUILD_TYPE="${2:-}"     # Optional: cvm

# Validate architecture
case "${ARCH_TYPE}" in
    x64|x86_64|amd64)
        ARCH_TYPE="x64"
        KERNEL_ARCH="x86_64"
        ;;
    arm64|aarch64)
        ARCH_TYPE="arm64"
        KERNEL_ARCH="arm64"
        CROSS_COMPILE="aarch64-linux-gnu-"
        ;;
    build|clean|help|--help|-h)
        # These are commands, not architectures - will be handled later
        ;;
    *)
        log_error "Unknown architecture: ${ARCH_TYPE}"
        log_error "Supported: x64, arm64"
        exit 1
        ;;
esac

# Build configuration
BUILD_OUTPUT="${BUILD_OUTPUT:-${KERNEL_ROOT}/build}"
MAKE_JOBS="${MAKE_JOBS:-$(nproc)}"

# Reproducible build environment
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1609459200}"
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
export TZ="UTC"

# Kernel-specific reproducible flags
export KBUILD_BUILD_TIMESTAMP="@${SOURCE_DATE_EPOCH}"
export KBUILD_BUILD_USER="${KBUILD_BUILD_USER:-builder}"
export KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST:-nixos}"
export KBUILD_BUILD_VERSION="1"

# Additional flags for reproducibility - map source paths to normalized locations
export KCFLAGS="-fdebug-prefix-map=/tmp/reproducible-kernel-build=/build/source"
export KAFLAGS="-fdebug-prefix-map=/tmp/reproducible-kernel-build=/build/source"

check_nix_shell() {
    if [ -z "${IN_NIX_SHELL:-}" ]; then
        log_warn "Not running in nix-shell. Entering nix development shell..."
        exec nix develop --command "$0" "$@"
    fi
}

prepare_build_dir() {
    log_info "Preparing build directory: ${BUILD_OUTPUT}"
    mkdir -p "${BUILD_OUTPUT}"

    # Create output Makefile if building out-of-tree
    if [ "${BUILD_OUTPUT}" != "${KERNEL_ROOT}" ]; then
        if [ ! -f "${BUILD_OUTPUT}/Makefile" ]; then
            cat > "${BUILD_OUTPUT}/Makefile" << EOF
# Automatically generated by nix-build.sh
export KBUILD_OUTPUT = ${BUILD_OUTPUT}
include ${KERNEL_ROOT}/Makefile
EOF
        fi
    fi
}

configure_kernel() {
    log_info "Configuring kernel for ${ARCH_TYPE}..."

    cd "${KERNEL_ROOT}"

    # Handle CVM build type
    if [ "${BUILD_TYPE}" = "cvm" ]; then
        log_info "CVM build requested - merging CVM config"
        "${KERNEL_ROOT}/Microsoft/merge-cvm-config.sh"
    fi

    # Select config based on architecture
    local arch_config="${KERNEL_ROOT}/Microsoft/hcl-${ARCH_TYPE}.config"

    if [ ! -f "${arch_config}" ]; then
        log_error "Config not found: ${arch_config}"
        exit 1
    fi

    # Use CONFIG_FILE_OVERRIDE if explicitly set, otherwise use detected arch config
    if [ -n "${CONFIG_FILE_OVERRIDE:-}" ]; then
        log_info "Using CONFIG_FILE_OVERRIDE: ${CONFIG_FILE_OVERRIDE}"
        cp "${CONFIG_FILE_OVERRIDE}" "${BUILD_OUTPUT}/.config"
    else
        log_info "Using config: ${arch_config}"
        cp "${arch_config}" "${BUILD_OUTPUT}/.config"
    fi

    # Update config for current kernel version
    make O="${BUILD_OUTPUT}" olddefconfig
}

build_kernel() {
    log_info "Building kernel with ${MAKE_JOBS} parallel jobs..."
    log_info "Architecture: ${ARCH_TYPE} (ARCH=${KERNEL_ARCH})"
    log_info "Reproducible build settings:"
    log_info "  SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
    log_info "  KBUILD_BUILD_USER=${KBUILD_BUILD_USER}"
    log_info "  KBUILD_BUILD_HOST=${KBUILD_BUILD_HOST}"

    cd "${KERNEL_ROOT}"

    # Prepare make arguments
    local MAKE_ARGS=()
    MAKE_ARGS+=("ARCH=${KERNEL_ARCH}")
    if [ -n "${CROSS_COMPILE:-}" ]; then
        MAKE_ARGS+=("CROSS_COMPILE=${CROSS_COMPILE}")
        log_info "  CROSS_COMPILE=${CROSS_COMPILE}"
    fi

    # Build kernel image
    make O="${BUILD_OUTPUT}" -j"${MAKE_JOBS}" \
        "${MAKE_ARGS[@]}" \
        KBUILD_BUILD_TIMESTAMP="${KBUILD_BUILD_TIMESTAMP}" \
        KBUILD_BUILD_USER="${KBUILD_BUILD_USER}" \
        KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST}" \
        KBUILD_BUILD_VERSION="${KBUILD_BUILD_VERSION}" \
        KCFLAGS="${KCFLAGS}" \
        KAFLAGS="${KAFLAGS}"

    # Build modules
    log_info "Building kernel modules..."
    make O="${BUILD_OUTPUT}" -j"${MAKE_JOBS}" modules \
        "${MAKE_ARGS[@]}" \
        KBUILD_BUILD_TIMESTAMP="${KBUILD_BUILD_TIMESTAMP}" \
        KBUILD_BUILD_USER="${KBUILD_BUILD_USER}" \
        KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST}" \
        KBUILD_BUILD_VERSION="${KBUILD_BUILD_VERSION}"
}

save_build_info() {
    log_info "Saving build information..."

    cat > "${BUILD_OUTPUT}/build-info.txt" << EOF
Build Information
=================
Build Date: $(date -u -d "@${SOURCE_DATE_EPOCH}" '+%Y-%m-%d %H:%M:%S UTC')
Kernel Version: $(make --no-print-directory -C "${KERNEL_ROOT}" O="${BUILD_OUTPUT}" kernelrelease)
Git Commit: $(cd "${KERNEL_ROOT}" && git rev-parse HEAD 2>/dev/null || echo "N/A")
Git Branch: $(cd "${KERNEL_ROOT}" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")

Reproducible Build Settings:
  SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
  KBUILD_BUILD_USER=${KBUILD_BUILD_USER}
  KBUILD_BUILD_HOST=${KBUILD_BUILD_HOST}
  KBUILD_BUILD_VERSION=${KBUILD_BUILD_VERSION}

Environment:
  LANG=${LANG}
  LC_ALL=${LC_ALL}
  TZ=${TZ}

Build Flags:
  KCFLAGS=${KCFLAGS}
  KAFLAGS=${KAFLAGS}

Build completed at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
EOF

    log_info "Build info saved to: ${BUILD_OUTPUT}/build-info.txt"
}

compute_checksums() {
    log_info "Computing checksums..."

    cd "${BUILD_OUTPUT}"

    # Find kernel image (different architectures use different names)
    KERNEL_IMAGE=""
    for img in arch/*/boot/Image arch/*/boot/bzImage arch/*/boot/zImage vmlinux; do
        if [ -f "$img" ]; then
            KERNEL_IMAGE="$img"
            break
        fi
    done

    if [ -n "${KERNEL_IMAGE}" ]; then
        sha256sum "${KERNEL_IMAGE}" > "${BUILD_OUTPUT}/kernel-image.sha256"
        log_info "Kernel image checksum saved to: ${BUILD_OUTPUT}/kernel-image.sha256"
    else
        log_warn "No kernel image found for checksum"
    fi
}

main() {
    log_info "Starting reproducible kernel build..."
    log_info "Kernel source: ${KERNEL_ROOT}"
    log_info "Build output: ${BUILD_OUTPUT}"
    log_info "Reproducible environment:"
    log_info "  SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
    log_info "  KBUILD_BUILD_USER=${KBUILD_BUILD_USER}"
    log_info "  KBUILD_BUILD_HOST=${KBUILD_BUILD_HOST}"

    # Set environment for reproducibility
    export KBUILD_BUILD_TIMESTAMP="${KBUILD_BUILD_TIMESTAMP}"
    export KBUILD_BUILD_USER="${KBUILD_BUILD_USER}"
    export KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST}"
    export KBUILD_BUILD_VERSION="${KBUILD_BUILD_VERSION}"
    export KCFLAGS="${KCFLAGS}"
    export KAFLAGS="${KAFLAGS}"
    
    # Create normalized symlink for reproducible paths
    # This ensures the embedded vDSO library path is consistent across machines
    NORMALIZED_ROOT="/tmp/reproducible-kernel-build"
    NORMALIZED_BUILD="/tmp/reproducible-build-output"
    
    # Clean up any existing symlinks/directories
    rm -rf "${NORMALIZED_ROOT}" "${NORMALIZED_BUILD}"
    
    ln -sf "${KERNEL_ROOT}" "${NORMALIZED_ROOT}"
    ln -sf "$(realpath "${KERNEL_ROOT}/..")/build" "${NORMALIZED_BUILD}"
    
    # Override BUILD_DIR to use normalized path (build-hcl-kernel.sh uses this if set)
    export BUILD_DIR="${NORMALIZED_BUILD}"
    export LINUX_SRC="${NORMALIZED_ROOT}"
    
    cd "${NORMALIZED_ROOT}"

    # Handle CVM build if requested
    if [ "${BUILD_TYPE}" = "cvm" ]; then
        log_info "Building with CVM config..."
        "${NORMALIZED_ROOT}/Microsoft/merge-cvm-config.sh"
    fi

    # Invoke the existing build-hcl-kernel.sh script
    log_info "Invoking build-hcl-kernel.sh..."
    "${NORMALIZED_ROOT}/Microsoft/build-hcl-kernel.sh" "${ARCH_TYPE}"
    
    # Clean up symlinks
    rm -f "${NORMALIZED_ROOT}"
    rm -f "${NORMALIZED_BUILD}"

    log_info "Build completed successfully!"
    log_info "Build artifacts are in: ${BUILD_OUTPUT}"
}

# Handle command line arguments
# Determine command (3rd arg for arch builds, or 1st arg if no arch specified)
COMMAND="${3:-build}"
if [ "${ARCH_TYPE}" = "build" ] || [ "${ARCH_TYPE}" = "clean" ] || [ "${ARCH_TYPE}" = "help" ] || [ "${ARCH_TYPE}" = "--help" ] || [ "${ARCH_TYPE}" = "-h" ]; then
    COMMAND="${ARCH_TYPE}"
    ARCH_TYPE="x64"  # Reset to default
fi
if [ "${BUILD_TYPE}" = "build" ] || [ "${BUILD_TYPE}" = "clean" ] || [ "${BUILD_TYPE}" = "help" ]; then
    COMMAND="${BUILD_TYPE}"
    BUILD_TYPE=""
fi

case "${COMMAND}" in
    build)
        main
        ;;
    clean)
        log_info "Cleaning build directory: ${BUILD_OUTPUT}"
        rm -rf "${BUILD_OUTPUT}"
        log_info "Clean completed"
        ;;
    help|--help|-h)
        echo "Usage: $0 [ARCH] [BUILD_TYPE] [COMMAND]"
        echo ""
        echo "Arguments:"
        echo "  ARCH        - Architecture: x64, arm64 (default: x64)"
        echo "  BUILD_TYPE  - Build type: cvm (optional)"
        echo "  COMMAND     - Command: build, clean, help (default: build)"
        echo ""
        echo "Examples:"
        echo "  $0 x64           - Build for x64"
        echo "  $0 arm64         - Build for arm64"
        echo "  $0 x64 cvm       - Build for x64 with CVM config"
        echo "  $0 arm64 cvm     - Build for arm64 with CVM config"
        echo ""
        echo "Commands:"
        echo "  build  - Build the kernel (default)"
        echo "  clean  - Clean build artifacts"
        echo "  help   - Show this help message"
        echo ""
        echo "Environment variables:"
        echo "  BUILD_OUTPUT        - Build output directory (default: ./build)"
        echo "  MAKE_JOBS           - Number of parallel jobs (default: nproc)"
        echo "  CONFIG_FILE_OVERRIDE - Override config file (default: auto-detect Microsoft config)"
        echo "  SOURCE_DATE_EPOCH   - Timestamp for reproducible builds"
        echo "  KBUILD_BUILD_USER   - Username for kernel build"
        echo "  KBUILD_BUILD_HOST   - Hostname for kernel build"
        ;;
    *)
        log_error "Unknown command: $1"
        log_info "Run '$0 help' for usage information"
        exit 1
        ;;
esac
